var table1 = [
	['column1', 'column2', 'column3', 'column4'],
	['data1', 3, 'two', 5],
	['data2', 4, 'three', 48]
];

var table2 = [
	['set 2 column1', 'column2', 'column3'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three'],
	['data1', 2, 'three']
];

export {table1, table2};